treatments2022 <- c("Barley_Pea_C", 
                    "Barley_Lupine_C", 
                    "Barley_Faba_C", 
                    "Rye_Pea_C",
                    "Rye_Lupine_C",
                    "Rye_Faba_C",
                    "Triticale_Pea_C",
                    "Triticale_Lupine_C",
                    "Triticale_Faba_C",
                    "Wheat_Pea_C",
                    "Wheat_Lupine_C",
                    "Wheat_Faba_C",
                    "Barley_Pea_L", 
                    "Barley_Lupine_L", 
                    "Barley_Faba_L", 
                    "Rye_Pea_L",
                    "Rye_Lupine_L",
                    "Rye_Faba_L",
                    "Triticale_Pea_L",
                    "Triticale_Lupine_L",
                    "Triticale_Faba_L",
                    "Wheat_Pea_L",
                    "Wheat_Lupine_L",
                    "Wheat_Faba_L",
                    "Barley",
                    "Rye",
                    "Triticale",
                    "Wheat",
                    "Pea",
                    "Lupine",
                    "Faba")

treatments2023A <- c("1T:1F_T", 
                     "1T:1F_F", 
                     "1T:3F_T",
                     "1T:3F_F",
                     "3T:1F_T", 
                     "3T:1F_F",
                     "TF-M_T", 
                     "TF-M_F", 
                     "T+", 
                     "F+", 
                     "T", 
                     "F")

treatments2023B <- c("T",
                     "1T:1F_T",
                     "1T:1F_F",
                     "TF-M_T",
                     "TF-M_F",
                     "F",
                     #"T-25",
                     #"1T:1F-25_T",
                     #"1T:1F-25_F",
                     #"F-25",
                     "T-375",
                     "1T:1F-375_T",
                     "1T:1F-375_F",
                     "TF-M-375_T",
                     "TF-M-375_F",
                     "F-375")

treatments2024 <- c("1T:1F_T",
                    "1T:1F_F",
                    "W",
                    "T",
                    "F")

rowTypes2023A <- c("1T:1F_T", 
                   "1T:1F_F", 
                   "1T:3F_T", 
                   #"1T:3F_F", 
                   "1T:3F_FA",
                   "1T:3F_FM",
                   #"3T:1F_T",
                   "3T:1F_TA", 
                   "3T:1F_TM", 
                   "3T:1F_F", 
                   "TF-M_T", 
                   "TF-M_F", 
                   "T+", 
                   "F+", 
                   "T", 
                   "F")